chords = ['ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE', 'MAJ THREE', 'FOUR', 'MIN FOUR', 'ONE']



